### PR TITLE
Add Map Alleyways

### PR DESCRIPTION
**Pull request by Paindeluxe**
This is an extension/sequel to the map https://github.com/nzp-team/nzportable/discussions/173

It contains rather tight Alleyways and Streets which you need to fend off the hordes of undead, and it's generally more on the semi difficult side.

Preview Images
fte-20230327225107-0
fte-20230329144756-0
fte-20230227172732-0

https://github.com/nzp-team/nzportable/discussions/279

### CODE REVIEW

**Comment by MotoLegacy** [comment]
Can't accept, this includes copyrighted material (official Perk-A-Cola jingles). Please make sure you verify the lack of copyrighted material before making a Pull Request.

Additionally, if you wish to open a new one, ensure that the loading screen graphics outside of FTE are stretched to 512x256, as it is more efficient on video memory.

**Comment by Paindeluxe** [comment]
I forgot about that my bad

**Comment by Naievil** [comment]
That's too bad! I really looked forward to playing this. @Paindeluxe do you feel the map would have the same (or similar) feeling without the jingles?

**Comment by Paindeluxe** [comment]
> That's too bad! I really looked forward to playing this. @Paindeluxe do you feel the map would have the same (or similar) feeling without the jingles?

I honestly think that the jingles were just a cherry on top, so I think it'll be fine without them.
I may retry the pull request tomorrow.

**Pull request closed without merging**
