### PR TITLE
MAPS: Fix clipping on NDU

### PR DESCRIPTION
**Pull request by DerpedCrusader**
put clip brushes around noclip brushes

image

### CODE REVIEW

**Comment by MotoLegacy** [comment]
Please change the pull request title to meet our standards. Additionally, can you confirm that you built vis with `-maxdistance 750`?

**Review by MotoLegacy — CHANGES_REQUESTED** [review]
See comment

**Comment by DerpedCrusader** [comment]
i can confirm that i have that set
image

**Review by MotoLegacy — APPROVED** [review]
Thanks for confirming and changing the title. LGTM

**Pull request merged**
