### PR TITLE
MAPS: Boxxer touch up

### PR DESCRIPTION
**Pull request by DerpedCrusader**
moved wall weapons to standard height
replaced PAP machine with the new model
made zombies only spawn after teddy is shot
made teddy door more obvious

### CODE REVIEW

**Comment by MotoLegacy** [comment]
Please add some screenshots so I can see these changes quickly. Additionally, do the perks also need updated to use their new models and stings?

**Comment by MotoLegacy** [comment]
> made zombies only spawn after teddy is shot
made teddy door more obvious

Does this apply to all of them in the map or just the ones behind the door?

**Comment by DerpedCrusader** [comment]
> > made zombies only spawn after teddy is shot
> made teddy door more obvious
> 
> Does this apply to all of them in the map or just the ones behind the door?

Sorry for the confusion, yes, just the ones behind the door, the ones in the starting room are active at the start

**Comment by DerpedCrusader** [comment]
> Please add some screenshots so I can see these changes quickly. Additionally, do the perks also need updated to use their new models and stings?

Didn't see this until right now, I can take screenshots when I get home

The perk machines already used the new models, but if they didn't have the stings before, I can make sure to check and add them tonight

**Comment by DerpedCrusader** [comment]
I know it's technically a l4q arrow, but I didn't want to use the "Power" arrow

image

**Comment by MotoLegacy** [comment]
Awesome, looks good to me, thanks for your work

**Pull request merged**
